// ASTEN VALE ARCHIVES — Vault Configuration
// Auto-generated by admin panel. Edit via the admin dashboard, not directly.

const SEASONS_CONFIG = [
  {
    id: "season1",
    title: "Season One",
    subtitle: "The Lantern at Black Pine",
    totalCases: 12,
    digits: [17,27,43,91,12,56,84,33,72,18,49,65],
    cases: [
      {
        id: "001",
        title: "Lantern at Black Pine",
        url: "case.html?id=1",
        released: true,
        scene: "lantern",
        releaseDate: null,
        desc: ["A remote cabin. A missing hiker.","And a light that wasn't supposed to be there."],
        gradient: ["#c8853a","#1a100a"],
        streaming: {}
      },
      {
        id: "002",
        title: "The Hollow Letter",
        url: "case.html?id=2",
        released: true,
        scene: "letter",
        releaseDate: null,
        desc: ["A letter with no return address.","A message that was never meant to be read."],
        gradient: ["#8a4a20","#1a100a"],
        streaming: {}
      },
      {
        id: "003",
        title: "The Rusted Key",
        url: "case.html?id=3",
        released: true,
        scene: "key",
        releaseDate: null,
        desc: ["A key found in the ruins.","It opens more than one door."],
        gradient: ["#7a5a18","#1a0e08"],
        streaming: {}
      },
      {
        id: "004",
        title: "The Widow Knows",
        url: "case.html?id=4",
        released: true,
        scene: "church",
        releaseDate: null,
        desc: ["A church. A bell toll.","And a woman who won't say what she saw."],
        gradient: ["#3a2a4a","#0c0a10"],
        streaming: {}
      },
      {
        id: "005",
        title: "Three Minutes Past",
        url: "case.html?id=5",
        released: false,
        scene: "clock",
        releaseDate: null,
        desc: ["Three minutes unaccounted for.","Every clock in town stopped at the same time."],
        gradient: ["#2a3a3a","#080c0c"],
        streaming: {}
      },
      {
        id: "006",
        title: "Across Pine Hollow",
        url: "case.html?id=6",
        released: false,
        scene: "forest",
        releaseDate: null,
        desc: ["Something crossed the hollow.","No one agrees on what it was."],
        gradient: ["#1a2a1a","#080c08"],
        streaming: {}
      },
      {
        id: "007",
        title: "Stranger's Matchbook",
        url: "case.html?id=7",
        released: false,
        scene: "matchbook",
        releaseDate: null,
        desc: ["A matchbook from a town that doesn't exist.","Found in the pocket of a dead man."],
        gradient: ["#3a2a1a","#0c0808"],
        streaming: {}
      },
      {
        id: "008",
        title: "Church Bell Never Rang",
        url: "case.html?id=8",
        released: false,
        scene: "bell",
        releaseDate: null,
        desc: ["It was supposed to ring at noon.","The whole town heard the silence instead."],
        gradient: ["#2a2a3a","#080810"],
        streaming: {}
      },
      {
        id: "009",
        title: "Cabin Without Smoke",
        url: "case.html?id=9",
        released: false,
        scene: "cabin",
        releaseDate: null,
        desc: ["The fire was lit. The smoke never came.","Someone else was in that cabin."],
        gradient: ["#2a1a1a","#0c0808"],
        streaming: {}
      },
      {
        id: "010",
        title: "Westbound Shadows",
        url: "case.html?id=10",
        released: false,
        scene: "road",
        releaseDate: null,
        desc: ["They all left heading west.","None of them arrived."],
        gradient: ["#1a1a2a","#080810"],
        streaming: {}
      },
      {
        id: "011",
        title: "Name in the Snow",
        url: "case.html?id=11",
        released: false,
        scene: "snow",
        releaseDate: null,
        desc: ["A name written in the snow.","Gone by morning. Remembered by no one."],
        gradient: ["#2a2a2a","#0a0a0c"],
        streaming: {}
      },
      {
        id: "012",
        title: "Black Pine Files",
        url: "case.html?id=12",
        released: false,
        scene: "files",
        releaseDate: null,
        desc: ["Everything that was hidden.","The file that closes the case — or opens it."],
        gradient: ["#1a1a1a","#080808"],
        streaming: {}
      }
    ],
    badges: [],
    bonusRewards: [],
    completionText: [],
    stats: []
  }
];
